# Generated by Django 5.1.6 on 2025-02-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_name', models.CharField(max_length=100)),
                ('employe_add', models.CharField(max_length=100)),
                ('empoye_number', models.IntegerField()),
            ],
        ),
    ]
