# Generated by Django 5.1.6 on 2025-02-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empoye_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='employe_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
