# Generated by Django 5.1.6 on 2025-02-19 03:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_remove_employee_empoye_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
