# Generated by Django 5.1.6 on 2025-02-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
